name: Build Debug

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  BuildDebug:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive --force

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-download-base-url: 'https://github.com/MetaCubeX/go/releases/download/build'
          go-version: '1.26'

      - name: Apply Patches
        run: |
          cd $(go env GOROOT)
          for p in $GITHUB_WORKSPACE/.github/patch/*.patch; do patch --verbose -p 1 < "$p" || true; done

      - name: Update CA
        run: |
          sudo apt-get update && sudo apt-get install -y ca-certificates
          sudo update-ca-certificates
          mkdir -p core/src/foss/golang/clash/component/ca
          cp -f /etc/ssl/certs/ca-certificates.crt core/src/foss/golang/clash/component/ca/ca-certificates.crt || true

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ys-apk
          path: app/build/outputs/apk/**/*.apk
